services:
  # Web Service (Main Application)
  - type: web
    name: salone-bellezza
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    # Prevent worker timeouts and 502 errors
    maxDeployments: 1
    # Health check settings
    healthCheckGracePeriodSeconds: 60
    healthCheckIntervalSeconds: 30
    healthCheckTimeoutSeconds: 10
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: salone-db
          property: connectionString

# PostgreSQL Database
databases:
  - name: salone-db
    plan: free
    databaseName: salone_bellezza
    user: salone_user 